### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by obriena** [crushlovely/Amaro#31]
Hi! when I started working with my project I changed the app from universal to iPhone, once it was done I decided I would go ahead and build a basic iPad version and re-enabled iPad support.  Now when I start the app I get this:
error: Script error: string index out of range
Please report this to https://github.com/crushlovely/Amaro/issues and include the details below.

Traceback (most recent call last):
  File "/Users/JustMe/Development/iOS/projects/MyApp/Scripts/GenerateStoryboardIDs.py", line 179, in <module>
    idList = IDList.fromFile(fn, prefix, needRestorationIDs)
  File "/Users/JustMe/Development/iOS/projects/MyApp/Scripts/GenerateStoryboardIDs.py", line 92, in fromFile
    res._addIds(viewControllerIds, cls.VIEW_CONTROLLER)
  File "/Users/JustMe/Development/iOS/projects/MyApp/Scripts/GenerateStoryboardIDs.py", line 78, in _addIds
    self._addId(id_, type_)
  File "/Users/JustMe/Development/iOS/projects/MyApp/Scripts/GenerateStoryboardIDs.py", line 73, in _addId
    variableName = lib.variableNameForString(id_, self._defaultPrefixes, suffixes)
  File "/Users/JustMe/Development/iOS/projects/MyApp/Scripts/AmaroLib.py", line 295, in variableNameForString
    result = self.smartLowerCase(result)
  File "/Users/JustMe/Development/iOS/projects/MyApp/Scripts/AmaroLib.py", line 305, in smartLowerCase
    return s[0].lower() + s[1:]
IndexError: string index out of range

I'm pretty confident this is something I did, I'm just not sure what it is.  

Thanks!

-Aaron

**Comment by obriena** [comment]
I was able to resolve this issue (thanks for being open source :) ) 

Just in case some one runs into this issue it seemed to be related to me having the same storyboardId & restorationId used for the main view controller in both storyboards.  I don' think there is anything in the Apple documentation against this but apparently it is problem with Amaro?  Not sure, the root cause but renaming the initial view controller's storyboardId seemed to fix the problem.
