### ISSUE TITLE
run into python script issue for generate storyboard ID

### ISSUE THREAD

**Issue by caoer** [crushlovely/Amaro#37]
report this: 
```
error: Script error: string index out of range
Please report this to https://github.com/crushlovely/Amaro/issues and include the details below.

Traceback (most recent call last):
  File "/Users/caoer115/Documents/Projects/DUMMY/Scripts/GenerateStoryboardIDs.py", line 179, in <module>
    idList = IDList.fromFile(fn, prefix, needRestorationIDs)
  File "/Users/caoer115/Documents/Projects/DUMMY/Scripts/GenerateStoryboardIDs.py", line 92, in fromFile
    res._addIds(viewControllerIds, cls.VIEW_CONTROLLER)
  File "/Users/caoer115/Documents/Projects/DUMMY/Scripts/GenerateStoryboardIDs.py", line 78, in _addIds
    self._addId(id_, type_)
  File "/Users/caoer115/Documents/Projects/DUMMY/Scripts/GenerateStoryboardIDs.py", line 73, in _addId
    variableName = lib.variableNameForString(id_, self._defaultPrefixes, suffixes)
  File "/Users/caoer115/Documents/Projects/DUMMY/Scripts/AmaroLib.py", line 297, in variableNameForString
    result = self.smartLowerCase(result)
  File "/Users/caoer115/Documents/Projects/DUMMY/Scripts/AmaroLib.py", line 307, in smartLowerCase
    return s[0].lower() + s[1:]
IndexError: string index out of range
```

**Comment by userow** [comment]
Obviously, the `.gitignore` is included in` Scripts` directory. So, when downloading a project from GIT - no `Scripts` directory is present.

**Comment by userow** [comment]
No, I was mistaken.

**Comment by userow** [comment]
Just commented this out in a build script. Probably, it is connected with xcode 8
